name: etc_flutter_boilerplate
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.4
  auto_route: ^3.2.4
  intl: ^0.17.0
  meta: ^1.7.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  json_annotation: ^4.4.0
  pretty_dio_logger: ^1.1.1
  flutter_secure_storage: 5.0.2
  google_fonts: ^2.3.1
  shared_preferences: ^2.0.13
  connectivity_plus: ^2.2.1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.12.0
  dependency_validator: ^3.1.2
  json_serializable:
  build_runner:
  flutter_gen_runner:
  freezed: ^1.1.1
  auto_route_generator: ^3.2.3
  logger:
  import_sorter: ^4.6.0
  flutter_lints: ^1.0.0

  #personal packages
  etc_uikit:
    path: ./packages/etc_uikit

## Install derry from https://pub.dev/packages/derry and run derry build, derry watch, derry gen
scripts: derry.yaml

# https://pub.dev/packages/flutter_gen, after new assets run derry gen
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  
  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/env/